name: bee_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^6.0.0
  provider: ^3.1.0+1
  cupertino_icons: ^0.1.2
  supernova_flutter_ui_toolkit: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
