name: bee_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0+1
  cupertino_icons: ^0.1.2
  supernova_flutter_ui_toolkit: ^0.0.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+6
  firebase_messaging: ^5.1.6
  firebase_storage: ^3.0.6
  overlay_support: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
